-- comment
-- app_data
CREATE USER app_data IDENTIFIED BY '^SaE9EqS!$%7Hj'
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_code
CREATE USER app_code IDENTIFIED BY '5kbq$eXuJGrZ&2'
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY '6yCh89F7tKa^u^'
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY '8s%8JpWPStwh%%'
ENABLE EDITIONS;

